spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adam/config.git
          username: ${git.username}
          password: ${git.password}
          skipSslValidation: true
          searchPaths: /repo
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
---
server:
  port: 3010