eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-service
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon-service
    feign:
      path: /feign/**
      serviceId: feign-service