version: '3.3'

services:

  nexus3:
    image: sonatype/nexus3:3.15.0
    container_name: nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    environment:
      NEXUS_CONTEXT: nexus
  
volumes:
  nexus-data: