version: "3.6"

services:

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - nginx-configs:/etc/nginx/conf.d/
volumes:
  nginx-configs: