version: '3.3'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-config:/pgadmin4

volumes:
  pgadmin-data:
  pgadmin-config: