version: '3.8'

services:

  sonarqube:
    image: sonarqube
    restart: always
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - 1022:22
      - 9001:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres12:5432/sonar
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_config:/opt/sonarqube/conf
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_config:
  sonarqube_logs:
  sonarqube_temp: