version: '3.7'

services:

  zipkin:
    image: openzipkin/zipkin
    restart: always
    container_name: zipkin
    hostname: zipkin
    ports:
      - 9411:9411
    environment:
      TZ: "Asia/Shanghai"
