version: '3.7'

services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  zkui:
    image: zkui
    container_name: zkui
    hostname: zkui
    ports:
      - 9090:9090
    depends_on:
      - zookeeper
    environment:
      ZKUI_ZK_SERVER: zookeeper:2181
